{% set name = "pyngrok" %}
{% set version = "7.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e43af9b2f21ceed8d213797028fe8823003f185b49792e4d383302365c81515

build:
  noarch: python
  entry_points:
    - ngrok=pyngrok.ngrok:main
    - pyngrok=pyngrok.ngrok:main
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - PyYAML >=5.1

test:
  imports:
    - pyngrok
  commands:
    - pip check
    - ngrok --help
    - pyngrok --help
  requires:
    - pip

about:
  home: https://github.com/alexdlaird/pyngrok
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python wrapper for ngrok
  description: |
    pyngrok is a Python wrapper for ngrok that manages its own binary and puts it on our path,
    making ngrok readily available from anywhere on the command line and via a convenient
    Python API.
  doc_url: https://pyngrok.readthedocs.io/
  dev_url: https://github.com/alexdlaird/pyngrok

extra:
  recipe-maintainers:
    - alexdlaird
